
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build
trigger:
  tags:
    include:
    - preRelease.*
    - Release.*
  branches:
    include:
    - dev
    - feature*
    - master


jobs:
  - job: Construction
    pool:
      vmImage: "windows-2019"
    steps:
      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
          echo "BUILD_BUILDNUMBER = $(Build.BuildNumber)"
          echo "BUILD_SOURCEBRANCH= $(Build.SourceBranch)"
          echo "BUILD_SOURCEBRANCHNAME= $(Build.SourceBranchName)"
          echo "BUILD_SOURCESDIRECTORY= $(Build.SourcesDirectory)"
          echo "BUILD_SOURCEVERSION= $(Build.SourceVersion)"

          set TAG_BUILD_SOURCEBRANCHNAME=$(Build.SourceBranchName)
          echo %TAG_BUILD_SOURCEBRANCHNAME%
          REM #for /F "tokens=4" %%A IN ('FINDSTR /C:"Successfully" tmpfile') DO SET VAR=%%A
          REM #IF (%TAG_BUILD_SOURCEBRANCHNAME% )
          for /f "tokens=2-2 delims=." %%A in ('echo %TAG_BUILD_SOURCEBRANCHNAME%') do (set version_first=%%A)
          for /f "tokens=3-3 delims=." %%A in ('echo %TAG_BUILD_SOURCEBRANCHNAME%') do (set version_second=%%A)
          for /f "tokens=4-4 delims=." %%A in ('echo %TAG_BUILD_SOURCEBRANCHNAME%') do (set version_third=%%A)
          
          rem #increse on 1
          set /a version_second_to_increase+=1
          rem #join again with the last element
          set versionPackage=%version_first%.%version_second_to_increase%.%set version_third%
          echo versionPackage %versionPackage%
          
        displayName: 'Run a multi-line script'