
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build
trigger:
  tags:
    include:
    - preRelease.*
    - Release.*
  branches:
    include:
    - dev
    - feature*
    - master
pool:
  vmImage: 'ubuntu-latest'

jobs:
  job:Construction
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo "BUILD_BUILDNUMBER = ${env:BUILD_BUILDNUMBER}"
        echo "BUILD_SOURCEBRANCH= $(Build.SourceBranch)"
        echo "BUILD_SOURCEBRANCHNAME= ${env:BUILD_SOURCEBRANCHNAME}"
        echo "BUILD_SOURCESDIRECTORY= ${env:BUILD_SOURCESDIRECTORY}"
        echo "BUILD_SOURCEVERSION= ${env:BUILD_SOURCEVERSION}"
      displayName: 'Run a multi-line script'