
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# specific branch build
trigger:
  tags:
    include:
    - preRelease.*
    - Release.*
  branches:
    include:
    - dev
    - feature*
    - master


jobs:
  - job: Construction
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo "BUILD_BUILDNUMBER = $(Build.BuildNumber)"
        echo "BUILD_SOURCEBRANCH= $(Build.SourceBranch)"
        echo "BUILD_SOURCEBRANCHNAME= $(Build.SourceBranchName)"
        echo "BUILD_SOURCESDIRECTORY= $(Build.SourcesDirectory)"
        echo "BUILD_SOURCEVERSION= $(Build.SourceVersion)"
      displayName: 'Run a multi-line script'